### ISSUE TITLE
Regarding the real car experiment

### ISSUE THREAD

**Issue by wahaha-1** [herolab-uga/mr-aoc#1]
I am very interested in the car system shown in the video. Could you please let me know if the car components can be made available? If possible, could you also provide the car's code?

**Comment by ramviyas** [comment]
Thanks for your interest. If you are referring to the simulated robots, then you can check out the Robotarium platform 
https://github.com/robotarium/robotarium_python_simulator

If you are interested in the real robots shown at the end of the video, please check out the HeRoSwarm repository:
https://github.com/herolab-uga/heroswarmv2

**Comment by wahaha-1** [comment]
thanks,i’ll try.
